apiVersion: v1
kind: Service
metadata:
  name: financesvc
  labels:
    app: app
spec:
  selector:
    app: app
  type: NodePort
  ports:
    - nodePort: 31111
      port: 8081
      targetPort: 8081

